### ISSUE TITLE
Folders seem to be created in the top level folder as well as the target directory

### ISSUE THREAD

**Issue by fusmatrs** [ScepticalRabbit/mooseherder#20]
Will have a look myself, but this is a reminder.

**Comment by ScepticalRabbit** [comment]
Might be worth attaching a minimal script snippet that replicates the issue. Based on current behaviour if you change the `base_dir` after calling 'herd.create_dirs()' weird and wonderful things will happen.

**Comment by fusmatrs** [comment]
Its seems to be when start_sweep() is called in run para.

**Comment by fusmatrs** [comment]
Hmm... I can't see why it's doing it. They're empty folders and don't seem to be effecting performance. Some times it's all N_moose folders, sometimes its less. It doesn't seem to be moose doing it, when I run it separately, but it does seem to occur as the call to moose is made. It's after the gmsh call definitely.

**Comment by fusmatrs** [comment]
It was the call to moose in the runner. It was running moose in the current working directory. For some reason moose takes this as a reason to make a directory in the current working directory (suspect due to the `--redirect-stdout` command) I've modified the `mooserunner.run()` and `herd.run_once()` methodsin my branch to pass the current `run-dir` to the runner and use that to call moose from the `run-dir`. Seems to solve the problem.

**Comment by ScepticalRabbit** [comment]
I pulled in these files into a test branch and it seems like this has broken the default behaviour where the `run_dir` is not specified as the input file is passed to the command line string with the path based on the `cwd`. I think we can remove the option based on `cwd` (which is the current default) because in general you want the `stdout` for each moose run in a separate directory and not have them all dump to the `mooseherder` root directory. This will mean we need to strip the relative path when creating the `herd._run_str` with the `assemble_run_str()` function.

**Comment by ScepticalRabbit** [comment]
This should have been fixed in the latest pull request and I have updated the examples with correct calls to `herd.create_dirs()` and `herd.clear_dirs()` so that this doesn't happen. Have also added functionality to `herd.set_base_dir()` to clear previous directories when changing the `base_dir`.
